# Generated by Django 2.2.7 on 2020-10-10 17:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Local', 'Local'), ('International', 'International'), ('Others', 'Others')], max_length=15)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('seat_limit', models.PositiveIntegerField(default=0)),
                ('entry_fee', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('post_on', models.DateTimeField(auto_now_add=True)),
                ('registration_link', models.URLField()),
                ('view_count', models.IntegerField(default=0)),
                ('banner', models.ImageField(upload_to='Event/')),
                ('event_organizar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_view', models.ManyToManyField(blank=True, related_name='event_view', to=settings.AUTH_USER_MODEL)),
                ('interested', models.ManyToManyField(blank=True, related_name='interested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventManager')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='events.EventComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
