# Generated by Django 2.2.7 on 2020-10-10 17:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fellowship', 'Fellowship'), ('Internship', 'Internship'), ('Research Assistant', 'Research Assistant'), ('Teacher Assistant', 'Teacher Assistant'), ('Trainee', 'Trainee')], max_length=30)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
                ('details', ckeditor.fields.RichTextField()),
                ('scope_counter', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='scope/')),
                ('url', models.URLField(blank=True)),
                ('love', models.ManyToManyField(blank=True, related_name='scope_love', to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(blank=True, related_name='scope_like', to=settings.AUTH_USER_MODEL)),
                ('scope_viewer', models.ManyToManyField(blank=True, related_name='scope_viewer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scope.ScopeManage')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='scope.ScopeComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
