# Generated by Django 2.2.7 on 2020-10-10 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=30)),
                ('book_edition', models.PositiveIntegerField(default=1)),
                ('book_publish', models.DateField()),
                ('category', models.CharField(choices=[('Art & Music', 'Art & Music'), ('Biographies', 'Biographies'), ('Business', 'Business'), ('Comics', 'Comics'), ('Computer & Tech', 'Computer & Tech'), ('Cooking', 'Cooking'), ('Science & Technology', 'Science & Technology'), ('Entertainment', 'Entertainment'), ('Health & Fitness', 'Health & Fitness'), ('Hobbies & Craft', 'Hobbies & Craft'), ('Horror', 'Horror'), ('Kids', 'Kids'), ('Literature & Fiction', 'Literature & Fiction'), ('Medical', 'Medical'), ('Religion', 'Religion'), ('Romance', 'Romance'), ('Sci-Fi & Fantasy', 'Sci-Fi & Fantasy'), ('Science & Math', 'Science & Math'), ('Sports', 'Sports'), ('Travel', 'Travel')], max_length=20)),
                ('book_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=10)),
                ('cover_pic', models.ImageField(upload_to='ebook_cover/')),
                ('book', models.FileField(upload_to='ebooks/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until_date', models.DateField(blank=True, null=True)),
                ('payment', models.FloatField(default=0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
